### ISSUE TITLE
Параметр задан неверно. (0x80070057)

### ISSUE THREAD

**Issue by Ainur777** [crypto-pro-web/crypto-pro-js#49]
Добрый день! Наткнулся на ваш пает и меня это обрадовало, всё хорошо работает, но вопрос по присоединению второй подписи, чтобы не делал ловлю ошибку:
![image](https://github.com/crypto-pro-web/crypto-pro-js/assets/43144793/0fad53f2-9cb8-4c0b-8204-9ae76fe32f6a)

**addDetachedSignature** - непонятно для меня как работает. Добавляю отпечаток, сообщение и генерируемый хэш.
Пример: сначала подписываю файл, через **createDetachedSignature** по первому отпечатку и хэшу, потом собираюсь подписать вторым отпечатком, совсем другой подписью через **addDetachedSignature**, получаю ошибку.
Объяснения я не нашёл, в самом классе указано:
![image](https://github.com/crypto-pro-web/crypto-pro-js/assets/43144793/4725fe56-0e33-475b-bb38-4469e5b85e86)
**_signedMessage_** - это ведь хэш ранее созданного сообщения?

Так же вы указали:
![image](https://github.com/crypto-pro-web/crypto-pro-js/assets/43144793/a166d088-cfdc-4d66-9e6e-bc16cdf6c56e)
Но этот issue не существует.

**Comment by Ainur777** [comment]
Вопрос закрыт. Не знаю с чем это связано, но работает только если подписываемый файл переименовывать в процессе. С оригиналом не работает.

**Comment by protoror** [comment]
Привет, можно поподробнее объяснить столкнулся с этой же проблемой и тоже ссылка в никуда
